version: '3'
#localproduct App
#assembly by Pushkin

services:
  localproduct:
    container_name: localproduct.app
    build: ./docker/php
    environment:
      - uid=${uid}
    depends_on:
      - postgres_localproduct
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project
      - ${SSH_DIR:-ssh_dir}:/root/.ssh

  nginx_localproduct:
    container_name: localproduct.nginx
    image: nginx:latest
    depends_on:
      - localproduct
    volumes:
      - .:/var/www/project
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    environment:
      VIRTUAL_HOST: ${DOCKER_SITE_URL}
      HTTPS_METHOD: nohttp

  postgres_localproduct:
    container_name: localproduct.database
    image: postgres:13-alpine
    ports:
      - "${DOCKER_DATABASE_PORT}:5432"
    volumes:
      - postgres_localproduct_pg_13_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: localproductdb
      TZ: Europe/Moscow

  memchached:
    container_name: localproduct.memcached
    image: memcached

  nodejs:
    container_name: localproduct.node
    image: node:14.3-alpine
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project

volumes:
  postgres_localproduct_pg_13_data: {}
  ssh_dir: {}

networks:
  default:
    external:
      name: proxy_proxy


